const data = [
    {
        id: 1,
        text:"JAPANESE PEACE",
        title: "JAPANESE PEACE ",
        price: 61.99 ,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090050_640.jpg"),
        variants: [
            {size: "20x24 inches",  price: 69},
            {size: "24x30 inches",  price: 79},
            {size: "20x24 inches",  price:59},
            {size: "24x30 inches",  price: 69},
        ],
    },
    {
        id: 2,
        text:"Romeo dok",
        title: "Romeo dok",
        price: 45.99,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090051_512.jpg"),
       

    },
    {
        id: 3,
        text:"INFINITE edition",
        title: "INFINITE edition",
        price: 55.99,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090059_575.jpg"),
    },
    {
        id: 4,
        text:"MATERIAL CLOCK",
        title: "MATERIAL CLOCK",
        price: 63.99,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090059_599.jpg"),
    },
    {
        id: 5,
        text:"SEA CLOCK",
        title: "SEA CLOCK",
        price: 82.99,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090059_753.jpg"),
    },
    {
        id: 6,
        text:"BEA EDITION",
        title: "BEA EDITION",
        price: 64.99,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090100_060.jpg"),
    },
    {
        id: 7,
        text:"SKY CLOCK",
        title: "SKY CLOCK",
        price: 75.99,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090108_705.jpg"),
        
    },
    {
        id: 8,
        text:"ace",
        title: "ace",
        price: 54.99,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090108_758.jpg"),
    },
    {
        id: 9,
        text:"EYES",
        title: "EYES",
        price: 35.99,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090108_900.jpg"),
    },
    {
        id: 10,
        text:"CLASSIC CLOCK",
        title: "CLASSIC CLOCK",
        price: 62.99,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090109_017.jpg"),
    },
    {
        id: 11,
        text:"RAINBOW CLOCK",
        title: "RAINBOW CLOCK",
        price: 62.99,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090109_226.jpg"),
    },
    {
        id: 12,
        text:"BLACK & WHITE",
        title: "BLACK & WHITE",
        price: 62.99,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090109_383.jpg"),
    },
    {
        id: 13,
        text:"2 EYE",
        title: "2 EYE",
        price: 62.99,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090109_595.jpg"),
    },
    {
        id: 14,
        text:"Peafowl",
        title: "Peafowl",
        price: 62.99,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090117_226.jpg"),
    },
    {
        id: 15,
        text:"DODI",
        title: "DODI",
        price: 62.99,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090117_288.jpg"),
    },
    {
        id: 16,
        text:"SUN SHINE",
        title: "SUN SHINE",
        price: 62.99,
        description:"Beautiful hand made pice with the (mind peace) design Powerful that come in all size and color   ",
        imageUrl: require("./productimg/IMG_20230513_090125_414.jpg"),
    },
   
];

export default data;